# Generated by Django 4.1 on 2024-08-19 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_create_date_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 9, 35, 31, 147263, tzinfo=datetime.timezone.utc)),
        ),
    ]
